# -*- coding: utf-8 -*-
"""Game_of_life.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G2r0f5Hhp9-6XIF4BHUkBBSNc-UD6CHo
"""

import random

w=10 #8+2=2 with padding
h=8  #8+2=2 with padding
grid=[[0 for x in range(w)] for y in range(h)]
grid=[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 1, 0, 0, 0, 1, 1, 0],
      [0, 0, 1, 1, 0, 1, 1, 0, 0, 0],
      [0, 1, 0, 1, 0, 0, 1, 0, 1, 0],
      [0, 0, 0, 1, 0, 0, 0, 1, 1, 0],
      [0, 0, 1, 1, 0, 1, 0, 1, 1, 0],
      [0, 0, 1, 0, 1, 1, 0, 1, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
     ]
#for i in range(1,7):
#    for j in range(1,9):
#     grid[i][j]=random.randint(0,1)


for i in range(len(grid)):
    print(grid[i])

def my_neighbours(grid,x,y):
 
  up=grid[x][y-1]
  down=grid[x][y+1]
  left=grid[x-1][y]
  right=grid[x+1][y]
  dur=grid[x+1][y-1]
  dul=grid[x-1][y-1]
  ddr=grid[x+1][y+1]
  ddl=grid[x-1][y+1]

  #print(up,down,left,right,dur,dul,ddr,ddl)
  total=up+down+left+right+dul+dur+ddr+ddl
  
  return total

#total=my_neighbours(grid,0,0)
#print (total)

def game_of_life(grid):
  w=10
  h=8
  new_grid=[[0 for x in range(w)] for y in range(h)] 
  
    
  for i in range(1,7):
    for j in range(1,9):
     # try:
      t=my_neighbours(grid,i,j)
      # print(i,j,t)
     # except IndexError:
      #  continue
      if (t<2):
        new_grid[i][j]=0
        #print(i,j,t,'dead',grid[i][j],new_grid[i][j])
      elif (t>3):
        new_grid[i][j]=0
        #print(i,j,t,'dead',grid[i][j],new_grid[i][j])
      elif ((t==3) and (grid[i][j]==0)):
        new_grid[i][j]=1
        #print(i,j,t,'alive',grid[i][j],new_grid[i][j])
      elif ((t==2) or (t==3)):
        new_grid[i][j]=grid[i][j]
        #print(i,j,t,'same',grid[i][j],new_grid[i][j])
      
  return new_grid

print('genration:0',sep='')
for i in range(1,len(grid)-1):
    print(grid[i][1:9])
print('\n')

for x in range(200):
  print('genration:',x+1,sep='')  
  new_gen=game_of_life(grid)  
  
  for i in range(1,7):
      print(new_gen[i][1:9])
  print('\n')
  grid=new_gen

